import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import AssistantButton from "@/app/components/AssistantButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hacknatics AI Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <AssistantButton />
        <Footer />
        </body>
    </html>
  );
}
